# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainlookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
