# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainlookup', '0002_auto_20180221_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='registrar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
