# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainlookup', '0003_auto_20180221_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='zone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
