# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domainlookup', '0004_auto_20180222_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_domains', models.IntegerField()),
            ],
        ),
    ]
